name: HandlebarsABAP release

on:
  release:
    types:
      - created

permissions:
  contents: write

env:
  ABAPGIT_CLASS_FILE: src/zcl_handlebars_abap.clas.abap
  RELEASE_CLASS_FILE: ZCL_HANDLEBARS_ABAP.abap

jobs:
  build:
    name: Create release file
    if: ${{ github.event_name == 'release' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set version
        shell: bash
        run: |
          sed 's/{{version}}/${{ github.event.release.tag_name }}/g' ${ABAPGIT_CLASS_FILE} > ${RELEASE_CLASS_FILE}

      - name: Upload
        run: |
          gh release upload ${{ github.event.release.tag_name }} ${RELEASE_CLASS_FILE}
        env:
            GH_TOKEN: ${{ github.TOKEN }}
